// Curated "best time to visit" data for popular travel destinations.
// months: 1 = January ... 12 = December (used to highlight the calendar strip)
const TRAVEL_DATA = [
  { country: "United States", currency: "USD", months: [4,5,9,10], best: "Apr–May & Sep–Oct", note: "Mild weather, fewer crowds than summer; avoid hurricane season (Jun–Nov) on the Gulf/East Coast." },
  { country: "Canada", currency: "CAD", months: [6,7,8,9], best: "Jun–Sep", note: "Warm summers open up the Rockies and coasts; winters are extremely cold outside ski season." },
  { country: "Mexico", currency: "MXN", months: [11,12,1,2,3,4], best: "Nov–Apr", note: "Dry season with warm, sunny days; rainy/hurricane season runs May–Oct." },
  { country: "Brazil", currency: "BRL", months: [9,10,11], best: "Sep–Nov", note: "Spring shoulder season — pleasant temps and lighter crowds before summer (Dec–Feb) peaks." },
  { country: "Argentina", currency: "ARS", months: [3,4,5,9,10,11], best: "Mar–May & Sep–Nov", note: "Autumn and spring avoid extreme Patagonian winter cold and summer heat further north." },
  { country: "Peru", currency: "PEN", months: [5,6,7,8,9], best: "May–Sep", note: "Dry season — best for Machu Picchu and the Andes; wet season is Dec–Mar." },
  { country: "Chile", currency: "CLP", months: [9,10,11,3,4], best: "Sep–Nov & Mar–Apr", note: "Shoulder seasons avoid summer crowds/heat and winter cold in Patagonia." },
  { country: "Colombia", currency: "COP", months: [12,1,2,7,8], best: "Dec–Feb & Jul–Aug", note: "Driest months; Colombia's near-equator climate is fairly stable year-round." },
  { country: "United Kingdom", currency: "GBP", months: [5,6,7,8,9], best: "May–Sep", note: "Warmest, driest months with the longest daylight hours." },
  { country: "Ireland", currency: "EUR", months: [5,6,9], best: "May–Jun & Sep", note: "Best chance of mild, drier weather while avoiding peak summer crowds." },
  { country: "France", currency: "EUR", months: [4,5,6,9,10], best: "Apr–Jun & Sep–Oct", note: "Pleasant temps, blooming countryside or harvest season, without August's heat and crowds." },
  { country: "Spain", currency: "EUR", months: [4,5,6,9,10], best: "Apr–Jun & Sep–Oct", note: "Avoids the intense July–August heat, especially inland and in the south." },
  { country: "Portugal", currency: "EUR", months: [3,4,5,9,10], best: "Mar–May & Sep–Oct", note: "Warm and sunny without peak-summer crowds on the Algarve and Lisbon coast." },
  { country: "Italy", currency: "EUR", months: [4,5,9,10], best: "Apr–May & Sep–Oct", note: "Comfortable sightseeing weather; skips the sweltering, packed month of August." },
  { country: "Germany", currency: "EUR", months: [5,6,7,8,9], best: "May–Sep", note: "Warmest months for outdoor sightseeing; late Sep brings Oktoberfest." },
  { country: "Netherlands", currency: "EUR", months: [4,5,6,9], best: "Apr–Jun & Sep", note: "April brings tulip season; late spring/early autumn keep mild, drier weather." },
  { country: "Switzerland", currency: "CHF", months: [6,7,8,12,1,2], best: "Jun–Aug (hiking) or Dec–Feb (ski)", note: "Two distinct seasons: summer for the Alps on foot, winter for skiing." },
  { country: "Austria", currency: "EUR", months: [5,6,9,12,1], best: "May–Jun, Sep & Dec–Jan", note: "Shoulder months for cities/hiking; December–January for Christmas markets and skiing." },
  { country: "Greece", currency: "EUR", months: [5,6,9,10], best: "May–Jun & Sep–Oct", note: "Warm Aegean weather while avoiding August's heat and ferry crowds." },
  { country: "Turkey", currency: "TRY", months: [4,5,9,10], best: "Apr–May & Sep–Oct", note: "Mild temperatures for Istanbul and Cappadocia; summer gets very hot inland." },
  { country: "Iceland", currency: "ISK", months: [6,7,8,2,3], best: "Jun–Aug (midnight sun) or Feb–Mar (northern lights)", note: "Summer for road trips and long daylight; late winter for aurora viewing." },
  { country: "Norway", currency: "NOK", months: [6,7,8], best: "Jun–Aug", note: "Midnight sun, fjord cruises and hiking trails are most accessible." },
  { country: "Sweden", currency: "SEK", months: [6,7,8], best: "Jun–Aug", note: "Long daylight and mild temperatures across Stockholm and the archipelago." },
  { country: "Denmark", currency: "DKK", months: [5,6,7,8], best: "May–Aug", note: "Warmest, sunniest stretch for Copenhagen and the coast." },
  { country: "Poland", currency: "PLN", months: [5,6,9], best: "May–Jun & Sep", note: "Mild weather for cities and countryside, avoiding summer crowds." },
  { country: "Czech Republic", currency: "CZK", months: [5,6,9], best: "May–Jun & Sep", note: "Pleasant Prague sightseeing weather without peak summer tourist density." },
  { country: "Croatia", currency: "EUR", months: [5,6,9], best: "May–Jun & Sep", note: "Warm Adriatic swimming weather while dodging the August coastal crush." },
  { country: "Russia", currency: "RUB", months: [5,6,7,8], best: "May–Aug", note: "White Nights in St. Petersburg and the mildest weather across the country." },
  { country: "South Africa", currency: "ZAR", months: [5,6,7,8,9], best: "May–Sep", note: "Dry winter is best for game viewing (Kruger) as animals gather at waterholes." },
  { country: "Egypt", currency: "EGP", months: [10,11,12,1,2,3,4], best: "Oct–Apr", note: "Cooler, dry season — summer heat in Luxor/Aswan can exceed 40°C." },
  { country: "Morocco", currency: "MAD", months: [3,4,5,9,10], best: "Mar–May & Sep–Oct", note: "Mild temperatures for the Sahara, Atlas Mountains and medina cities." },
  { country: "Kenya", currency: "KES", months: [7,8,9,1,2], best: "Jul–Sep & Jan–Feb", note: "Jul–Sep covers the Great Migration river crossings; Jan–Feb is dry and warm." },
  { country: "Tanzania", currency: "TZS", months: [6,7,8,9,1,2], best: "Jun–Sep & Jan–Feb", note: "Dry seasons are best for safaris and Kilimanjaro treks." },
  { country: "Nigeria", currency: "NGN", months: [11,12,1,2], best: "Nov–Feb", note: "Harmattan dry season brings lower humidity and less rain." },
  { country: "United Arab Emirates", currency: "AED", months: [11,12,1,2,3], best: "Nov–Mar", note: "Comfortably warm and dry; summer heat is extreme and humid." },
  { country: "Saudi Arabia", currency: "SAR", months: [11,12,1,2,3], best: "Nov–Mar", note: "Cooler desert temperatures make sightseeing far more comfortable." },
  { country: "Israel", currency: "ILS", months: [3,4,5,9,10], best: "Mar–May & Sep–Oct", note: "Mild, dry shoulder seasons across Jerusalem, Tel Aviv and the Negev." },
  { country: "India", currency: "INR", months: [10,11,12,1,2,3], best: "Oct–Mar", note: "Cool, dry season nationwide; avoids the summer heat and monsoon rains." },
  { country: "Nepal", currency: "NPR", months: [3,4,5,10,11], best: "Mar–May & Oct–Nov", note: "Clear mountain views and stable weather for trekking the Himalayas." },
  { country: "Sri Lanka", currency: "LKR", months: [12,1,2,3], best: "Dec–Mar", note: "Dry season on the west/south coasts and cultural triangle." },
  { country: "Thailand", currency: "THB", months: [11,12,1,2], best: "Nov–Feb", note: "Cool, dry season — hot season (Mar–May) and monsoon (Jun–Oct) are less comfortable." },
  { country: "Vietnam", currency: "VND", months: [11,12,1,2,3,4], best: "Nov–Apr", note: "Climate varies by region, but this window is generally dry across most of the country." },
  { country: "Cambodia", currency: "KHR", months: [11,12,1,2], best: "Nov–Feb", note: "Cool, dry season is ideal for exploring Angkor Wat." },
  { country: "Indonesia", currency: "IDR", months: [5,6,7,8,9], best: "May–Sep", note: "Dry season across Bali and most islands; wet season runs Nov–Mar." },
  { country: "Malaysia", currency: "MYR", months: [12,1,2,3], best: "Dec–Mar (west coast)", note: "Tropical and humid year-round; timing depends on which coast (monsoons alternate)." },
  { country: "Singapore", currency: "SGD", months: [2,3,4], best: "Feb–Apr", note: "Slightly drier stretch in a hot, humid, tropical climate year-round." },
  { country: "Philippines", currency: "PHP", months: [12,1,2,3,4], best: "Dec–Apr", note: "Dry season avoids typhoon risk, which peaks Jun–Nov." },
  { country: "China", currency: "CNY", months: [3,4,5,9,10,11], best: "Mar–May & Sep–Nov", note: "Spring and autumn bring mild temperatures across most major regions." },
  { country: "Japan", currency: "JPY", months: [3,4,10,11], best: "Mar–Apr & Oct–Nov", note: "Cherry blossoms in spring, colorful foliage in autumn, mild temperatures both times." },
  { country: "South Korea", currency: "KRW", months: [3,4,5,9,10], best: "Mar–May & Sep–Oct", note: "Spring blossoms and autumn foliage with comfortable temperatures." },
  { country: "Australia", currency: "AUD", months: [3,4,5,9,10,11], best: "Mar–May & Sep–Nov", note: "Autumn and spring avoid the intense summer heat and winter chill (seasons are reversed)." },
  { country: "New Zealand", currency: "NZD", months: [12,1,2,3], best: "Dec–Mar", note: "Southern Hemisphere summer — warmest weather for hiking and outdoor activities." },
  { country: "Fiji", currency: "FJD", months: [5,6,7,8,9,10], best: "May–Oct", note: "Dry season with lower humidity; cyclone season runs Nov–Apr." },
  { country: "China (Hong Kong)", currency: "HKD", months: [10,11,12], best: "Oct–Dec", note: "Cooler, drier and less humid than the sweltering summer months." },
  { country: "Taiwan", currency: "TWD", months: [10,11,3,4], best: "Oct–Nov & Mar–Apr", note: "Mild temperatures avoid summer typhoon season and winter chill in the north." },
  { country: "Pakistan", currency: "PKR", months: [3,4,10,11], best: "Mar–Apr & Oct–Nov", note: "Spring and autumn bring comfortable temperatures across most regions." },
  { country: "Bangladesh", currency: "BDT", months: [11,12,1,2], best: "Nov–Feb", note: "Cool, dry winter avoids monsoon flooding and summer humidity." },
  { country: "Iceland", currency: "ISK", months: [6,7,8], best: "Jun–Aug", note: "Warmest, most accessible months with nearly 24-hour daylight." },
  { country: "Finland", currency: "EUR", months: [6,7,8,2,3], best: "Jun–Aug or Feb–Mar", note: "Summer for the midnight sun and lakes; late winter for northern lights and skiing." },
  { country: "Hungary", currency: "HUF", months: [5,6,9], best: "May–Jun & Sep", note: "Mild Budapest sightseeing weather without peak summer heat and crowds." },
  { country: "Romania", currency: "RON", months: [5,6,9], best: "May–Jun & Sep", note: "Pleasant temperatures for Transylvania and the Carpathians." },
  { country: "Ukraine", currency: "UAH", months: [5,6,9], best: "May–Jun & Sep", note: "Check current travel advisories before planning any trip." },
  { country: "Costa Rica", currency: "CRC", months: [12,1,2,3,4], best: "Dec–Apr", note: "Dry season across most of the country; green (rainy) season runs May–Nov." },
  { country: "Jamaica", currency: "JMD", months: [12,1,2,3,4], best: "Dec–Apr", note: "Dry, sunny season; hurricane risk rises Jun–Nov." },
  { country: "Dominican Republic", currency: "DOP", months: [12,1,2,3,4], best: "Dec–Apr", note: "Dry season with lower humidity; avoids peak hurricane months." },
  { country: "Cuba", currency: "CUP", months: [11,12,1,2,3,4], best: "Nov–Apr", note: "Cooler, drier weather; hurricane season runs Jun–Nov." },
  { country: "Panama", currency: "PAB", months: [12,1,2,3,4], best: "Dec–Apr", note: "Dry season is best for the Caribbean and Pacific coasts alike." },
  { country: "Ecuador", currency: "USD", months: [6,7,8,9], best: "Jun–Sep (highlands) ", note: "Dry season in the Andes/Quito; Galápagos and Amazon vary — check sub-region." },
  { country: "Qatar", currency: "QAR", months: [11,12,1,2,3], best: "Nov–Mar", note: "Cooler, pleasant temperatures; summer is extremely hot and humid." },
  { country: "Jordan", currency: "JOD", months: [3,4,5,9,10], best: "Mar–May & Sep–Oct", note: "Mild desert temperatures for Petra and Wadi Rum, avoiding summer extremes." },
];

// Basic currency-code -> display name map (covers the codes above plus common majors)
const CURRENCY_NAMES = {
  USD: "US Dollar", EUR: "Euro", GBP: "British Pound", JPY: "Japanese Yen",
  CAD: "Canadian Dollar", AUD: "Australian Dollar", NZD: "New Zealand Dollar",
  CHF: "Swiss Franc", CNY: "Chinese Yuan", HKD: "Hong Kong Dollar", SGD: "Singapore Dollar",
  INR: "Indian Rupee", KRW: "South Korean Won", MXN: "Mexican Peso", BRL: "Brazilian Real",
  ZAR: "South African Rand", SEK: "Swedish Krona", NOK: "Norwegian Krone", DKK: "Danish Krone",
  PLN: "Polish Zloty", THB: "Thai Baht", TRY: "Turkish Lira", AED: "UAE Dirham",
  SAR: "Saudi Riyal", ILS: "Israeli Shekel", RUB: "Russian Ruble", IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit", PHP: "Philippine Peso", VND: "Vietnamese Dong", EGP: "Egyptian Pound",
  ARS: "Argentine Peso", CLP: "Chilean Peso", COP: "Colombian Peso", PEN: "Peruvian Sol",
  ISK: "Icelandic Krona", CZK: "Czech Koruna", HUF: "Hungarian Forint", RON: "Romanian Leu",
  UAH: "Ukrainian Hryvnia", NGN: "Nigerian Naira", KES: "Kenyan Shilling", TZS: "Tanzanian Shilling",
  MAD: "Moroccan Dirham", PKR: "Pakistani Rupee", BDT: "Bangladeshi Taka", NPR: "Nepalese Rupee",
  LKR: "Sri Lankan Rupee", KHR: "Cambodian Riel", TWD: "New Taiwan Dollar", QAR: "Qatari Riyal",
  JOD: "Jordanian Dinar", CRC: "Costa Rican Colon", JMD: "Jamaican Dollar", DOP: "Dominican Peso",
  CUP: "Cuban Peso", PAB: "Panamanian Balboa", FJD: "Fijian Dollar",
};
